In work, generate_checksum()

diff --git a/pkgbuild_update b/pkgbuild_update
--- a/pkgbuild_update
+++ b/pkgbuild_update
@@ -38,13 +38,6 @@ warning() {
     fi
 }
 
-warning2() {
-    if [ -z "${IGNORE_WARN}" ]; then
-	    local mesg=$1; shift
-	    printf "  -> $(gettext "WARNING:") ${mesg}\n" "$@" >&2
-    fi
-}
-
 error() {
 	local mesg=$1; shift
 	printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
@@ -123,7 +116,7 @@ source_safe() {
 
 
 # Extract the protocol from a source entry - return "local" for local sources
-# copy from makepkg
+# [copy from makepkg]
 get_protocol() {
 	if [[ $1 = *://* ]]; then
 		# strip leading filename
@@ -137,7 +130,7 @@ get_protocol() {
 	fi
 }
 
-# copy from makepkg
+# [copy from makepkg]
 get_downloadclient() {
 	local proto=$1
 
@@ -168,10 +161,10 @@ get_downloadclient() {
 
 # Download file
 # Arguments:
-#   $1, file url
-#   $2 [optional], file name to save as, default value is the
+#   - $1, file url
+#   - $2 [optional], file name to save as, default value is the
 #     base name of file url
-# copy from makepkg with some changes
+# [copy from makepkg with some changes]
 download_file() {
 	local url=$1
     local filename=$2
@@ -227,7 +220,7 @@ download_file() {
 
 # List keys in template file
 # Arguments:
-#   $1, the template file
+#   - $1, the template file
 listkey() {
     tplfile=$1
     if [ ! -e "${tplfile}" ]; then
@@ -241,18 +234,18 @@ BEGIN {
 
 keyreg {
     while ($0 ~ keyreg) {
-        key=gensub(keyreg, "\\2", "")
+        filename_key=gensub(keyreg, "\\2", "")
         $0=gensub(keyreg, "\\1\\3", "")
-        if (key in keys == 0) {
-            keys[key]=l++
+        if (filename_key in keys == 0) {
+            keys[filename_key]=l++
         }
     }
 }
 
 END {
     PROCINFO["sorted_in"] = "@val_num_asc"
-    for (key in keys) {
-        print key
+    for (filename_key in keys) {
+        print filename_key
     }
 }
 ' ${tplfile}
@@ -271,14 +264,18 @@ urldecode() {
 
 # Get latest file by parsing web page
 # Arguments:
-#   $1, url of the web page
-#   $2, regexp of the file name, used by "grep -oP" to get the last file
+#   - $1, url of the web page
+#   - $2, regexp of the file name, used by command "grep -o -P" and
+#     sort to get the last file
 get_latest_file_by_parsing_web_page() {
+    msg2 "$(gettext "Parsing web page to get latest package file name:")"
     local url=$1
     local filereg=$2
     
     abort_if_var_empty "${url}" "url"
     abort_if_var_empty "${filereg}" "filereg"
+    msg2 "  url: ${url}"
+    msg2 "  regexp: ${filereg}"
     
     # get web page content
     local get_page_cmd=$(printf "${GET_PAGE_CMD}" ${url})
@@ -286,27 +283,27 @@ get_latest_file_by_parsing_web_page() {
     
     # decode url and get latest file
     local matched_files=$(echo "${web_content}" | urldecode | grep -o -P ${filereg})
-    local latest_file=$(echo "${matched_files}" | sort -n | tail -1)
-    if [[ -z "${latest_file}" ]]; then
-        # get latest file failed
+    local latestfn=$(echo "${matched_files}" | sort -n | tail -1)
+    if [[ -z "${latestfn}" ]]; then
+        error "$(gettext "Get latest package file name failed")"
         return 1
     fi
     
-    printf "%s\n" "${latest_file}"
+    printf "%s\n" "${latestfn}"
 }
 
 # Generate PKGBUILD from template file
 # Arguments:
-#   $1, the template file, such as "PKGBUILD.template"
-#   $2 [optional], the key-values for template file,
+#   - $1, the template file, such as "PKGBUILD.template"
+#   - $2 [optional], the key-values for template file,
 #     and echo key-value own one line, such as:
 #       "key1=value1
 #        key2=value2
 #        key3=value3"
-#   $3 [optional], the output PKGBUILD file, default is in the same
+#   - $3 [optional], the output PKGBUILD file, default is in the same
 #     directory with template file
 generate_pkgbuild() {
-    msg2 "$(gettext "Starting generate_pkgbuild()...")"
+    msg2 "$(gettext "Generating PKGBUILD from template file...")"
     local tplfile=$1
     local keyvalues=$2
     local pkgfile=$3
@@ -319,7 +316,7 @@ generate_pkgbuild() {
     fi
     
     # replace keys to values in template file to generate PKGBUILD
-    # file, if key is undefined, just replace to empty
+    # file, if filename_key is undefined, just replace to empty
     msg2 "$(gettext "Key-values: %s")" "$(joinline ${keyvalues})"
     msg2 "$(gettext "Generate '%s' through template file '%s'")" "${pkgfile}" "${tplfile}"
     awk -v keyvalues_str="${keyvalues}" '
@@ -337,9 +334,9 @@ BEGIN {
 keyreg {
     tmpstr=$0
     while (tmpstr ~ keyreg) {
-        key=gensub(keyreg, "\\2", "", tmpstr)
-        if (key in keyvalues) {
-            value=keyvalues[key]
+        filename_key=gensub(keyreg, "\\2", "", tmpstr)
+        if (filename_key in keyvalues) {
+            value=keyvalues[filename_key]
             $0=gensub(keyreg, "\\1" value "\\3", "g")
         }
 
@@ -354,51 +351,100 @@ keyreg {
     # Check if all the template variables were replaced
     local keys=$(listkey ${pkgfile})
     if [ -n "${keys}" ]; then
-        warning "$(gettext "there are undefined keys in %s:")" "${pkgfile}"
-        warning2 "$(joinline ${keys})"
+        warning "$(gettext "there are undefined keys in %s: %s")" \
+            "${pkgfile}" "$(joinline ${keys})"
     fi
 }
 
-### Help Functions for Target Package
+generate_checksum() {
+	msg "$(gettext "Generating checksums for source files...")"
+    local file=$0
+    local integ=${INTEGRITY_CHECK}
+    
+	if ! type -p openssl >/dev/null; then
+		error "$(gettext "Cannot find the command '%s'")" "openssl"
+		return 1
+	fi
+    
+	case "$integ" in
+		md5|sha1|sha256|sha384|sha512) : ;;
+		*)
+			error "$(gettext "Invalid integrity algorithm '%s' specified")" "$integ"
+			return 1 ;;
+	esac
+    
+	local sum="$(openssl dgst -${integ} "${file}")"
+	sum=${sum##* }
+	printf "%s" "${sum}"
+}
 
+### Helper Functions for Target Package
+
+# Update package which living in other linux distro source site, and
+# get the latest package file name by parsing the web page
+# Need variables:
+#   - $FILE_DATA, a array with useful information to get the latest
+#     package file name, echo element own four fields which were
+#     separate by "::".
+#     The element format looks like as:
+#       "filename_key::checksum_key::url::file_regexp"
+#     Descripion of the format:
+#       - filename_key, the key name in template file corresponding to the
+#         package file name,
+#       - checksum_key, the check-sum's key name for the package file
+#       - url, the url of the web page which the package file place in
+#       - file_regexp, the regexp to get the latest package file name, will
+#         be used by command "grep -o -P".
+#     Here is an example:
+#       FILE_DATA=("filename1::md51::http://ftp.debian.org/debian/pool/main/h/hello::hello_.*?\.tar\.gz"
+#                  "filename2::md52::http://ftp.debian.org/debian/pool/main/h/hello-debhelper::hello-debhelper_.*?\.tar\.gz")
 # Arguments:
-#   $1, template file
-#   $2, url of the web page which package file place in
-#   $3, file name regexp, used by "grep -oP"
-#   $4, package version regexp, used by "grep -oP"
+#   - $1, template file
+#   - $2, package version regexp, used by "grep -o -P" in the first
+#     package file name
 update_package_in_source_site() {
-    msg "$(gettext "Starting update_package_in_source_site()...")"
+    msg "$(gettext "Updating package which living in source site...")"
     local tplfile=$1
-    local url=$2
-    local filereg=$3
-    local pkgverreg=$4
+    local pkgverreg=$2
     local keyvalues=""
     
+    abort_if_var_empty "${FILE_DATA[0]}" "FILE_DATA"
     abort_if_var_empty "${tplfile}" "tplfile"
-    abort_if_var_empty "${url}" "url"
-    abort_if_var_empty "${filereg}" "filereg"
     abort_if_var_empty "${pkgverreg}" "pkgverreg"
     msg2 "$(gettext "Updating %s...")" "${tplfile}"
     
-    # get latest package name
-    msg2 "$(gettext "Parsing web page to get latest package name: %s")" "${url}"
-    local latest_file=$(get_latest_file_by_parsing_web_page "${url}" "${filereg}") || \
-        { warning "$(gettext "update %s failed, skip it")" "${tplfile}"; return; }
-    abort_if_var_empty "${latest_file}" "latest_file"
-    keyvalues=$(printf "%s\n" "filename=${latest_file}")
+    # parse variable FILE_DATA to get each package file's latest name and check-sum
+    local mainfn=""
+    for d in "${FILE_DATA[@]}"; do
+        local filename_key="$(echo $d | awk -F '::' '{print $1}')"
+        local checksum_key="$(echo $d | awk -F '::' '{print $2}')"
+        local url="$(echo $d | awk -F '::' '{print $3}')"
+        local filereg="$(echo $d | awk -F '::' '{print $4}')"
+        
+        local latestfn
+        latestfn=$(get_latest_file_by_parsing_web_page "${url}" "${filereg}") || return 1
+        keyvalues=$(printf "%s\n%s" "${keyvalues}" "${filename_key}=${latestfn}")
+        
+        # download latest package file
+        local fileurl="${url}/${latestfn}"
+        local savefile="$(dirname ${tplfile})/${latestfn}"
+        download_file ${fileurl} ${savefile} || return 1
+        
+        # generate integrity checks
+        local checksum
+        checksum=$(generate_checksum ${savefile}) || return 1
+        keyvalues=$(printf "%s\n%s" "${keyvalues}" "${checksum_key}=${checksum}")
+        
+        # set first package as the main package, and mark its latest
+        # file name to get package version later
+        if [ -z "${mainfn}" ]; then
+            mainfn=${latestfn}
+        fi
+    done
     
     # get package version
-    local pkgver=$(echo "${latest_file}" | grep -o -P ${pkgverreg} | tail -1)
+    local pkgver=$(echo "${mainfn}" | grep -o -P ${pkgverreg} | tail -1)
     keyvalues=$(printf "%s\n%s" "${keyvalues}" "pkgver=${pkgver}")
-    
-    # download latest package
-    local fileurl="${url}/${latest_file}"
-    local savefile="$(dirname ${tplfile})/${latest_file}"
-    download_file ${fileurl} ${savefile}
-    
-    # generate integrity checks 
-    local md5=$(md5sum ${savefile} | awk '{print $1}')
-    keyvalues=$(printf "%s\n%s" "${keyvalues}" "md5=${md5}")
     
     # generate new PKGBUILD
     generate_pkgbuild "${tplfile}" "${keyvalues}"
@@ -414,6 +460,9 @@ shopt -s extglob
 
 # Default variables, can be overwrite
 IGNORE_WARN=""
+
+# File integrity checks to use. Valid: md5, sha1, sha256, sha384, sha512
+INTEGRITY_CHECK="md5"
 
 if [[ -z "${GET_PAGE_CMD}" ]]; then
     GET_PAGE_CMD='/usr/bin/curl -sfL --retry 3 --retry-delay 3 %s'
